title: SolTek
email: soltekdubai@protonmail.ch
description: >-
  Expert in solar power maintenance, repair, and consulting, with advanced monitoring of energy production and consumption applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://soltekdubai.github.io/soltek/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: soltekdubai

# Build settings
theme: jekyll-theme-cayman  # Using the Cayman theme locally
plugins:
  - jekyll-feed  # To generate RSS feed
  - jekyll-remote-theme  # For future remote theme use

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
